name: DCPhotographyandFilms
favicon: null
layout_spectrum: 0.17543
typography_spectrum: 0.82386
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: DCPhotographyandFilms
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#cfd0d2'
    - '#a5aab0'
    - '#696564'
    - '#0a0a0a'
    - '#3d3532'
  brandStrength: 0.75
  lightness: 0.5625
  saturation: 0.2072818216402084
  rhythmicContrast: 0.5623715699184686
purpose: []
