name: dcphotography
favicon: null
layout_spectrum: 0.09615277172997594
typography_spectrum: 0.79883
title: Fotografía de Bodas
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#cfd0d2'
    - '#a5aab0'
    - '#696564'
    - '#0a0a0a'
    - '#3d3532'
  brandStrength: 0.6875
  lightness: 0.5625
  saturation: 0.20728182164020836
  rhythmicContrast: 0.5623715699184686
purpose: []
